services:
  pangeeclusterdev:
    image: ghcr.io/opencmit/pangee-cluster-devcontainer:latest
    privileged: true
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../..:/workspaces:cached
      - "/etc/resolv.conf:/etc/resolv.conf"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "~/.ssh:/root/.ssh"
    ports:
      - "3322:22"
